# Site settings
title: Kotlin Korea
author: Kotlin Korea
email: hi@kotlin.kr
description: Kotlin 언어 한국 사용자 모임입니다.
url: "http://kotlin.kr"
username: kotlinkr
logo_svg: /assets/images/logo/kotlinkr.svg
logo_png: /assets/images/logo/kotlinkr.png
icon_png: /assets/images/logo/kotlinkr-icon.png
logo_size: 256
facebook_app_id: 172243503152254
google_analytics_id: UA-73838755-1
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
